language: cpp
os: 
  - linux
  - windows
  - osx

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: cmake --build .

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
