language: cpp
os: 
#  - linux
  - windows
#  - osx

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script:
     - devenv Test1.sln /build
#    - cmake --build .
#    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cp Test1 Test1-"$TRAVIS_OS_NAME" ; fi
#    - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then copy Debug\\Test1.exe Test1-"$TRAVIS_OS_NAME".exe; fi
#    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp Test1 Test1-"$TRAVIS_OS_NAME"; fi

#before_deploy:
#  # Set up git user name and tag this commit
#  - git config --local user.name "Travis_Building"
#  - git config --local user.email "Travis_Building"
#  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
#  - git tag $TRAVIS_TAG

#before_install:
#  - mv Test1 Test1-"$TRAVIS_OS_NAME"
#  - mv Test1.exe Test1-"$TRAVIS_OS_NAME".exe

#deploy:
#  provider: releases
#  api_key: $GH_KEY
#  file_glob: true
#  file: ./Test1*
#  skip_cleanup: true
  #on:
  #  repo: my-org/my-repo
  #  branches:    # ← new!
  #    only:      # ← new!
  #      - master # ← new!
#  on:
#    tags: true

