language: cpp
os: 
  - linux
#  - windows
#  - osx

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: cmake --build .

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Travis_Building"
  - git config --local user.email "Travis_Building"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GH_KEY
  file: build/Test*
  skip_cleanup: true
  on:
  - branch: master
  #on:
  #  tags: true
